import "regenerator-runtime/runtime";
import type { Metadata } from "next";
import { Inter, Poppins, Dancing_Script } from "next/font/google";
import "./globals.css";

import { Providers } from "../providers";
import AiBotMain from "@/components/AiChatBot/AiBotMain";
import { Analytics } from "@vercel/analytics/react";
import { notFound } from "next/navigation";
import { NextIntlClientProvider } from "next-intl";
import { locales } from "@/navigation";
import ToastProvider from "@/utils/ToastProvider";
import 'react-datetime-picker/dist/DateTimePicker.css';
import 'react-calendar/dist/Calendar.css';
import 'react-clock/dist/Clock.css';


const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  display: "swap",
});

const poppins = Poppins({
  subsets: ["latin"],
  variable: "--font-poppins",
  display: "swap",
  weight: "400",
});

const dancingScript = Dancing_Script({
  subsets: ["latin"],
  variable: "--font-dancing-script",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Clinica San Miguel",
  description: "Generated by create next app",
};

export default async function RootLayout(props: {
  children: React.ReactNode;
  params: Promise<{ locale: string }>; // ✅ handle param as a Promise
}) {
  const { children, params } = props;

  const resolvedParams = await params; // ✅ await it!
  const { locale } = resolvedParams;

  // 🐛 Optional Debug
  console.log("[layout.tsx] Awaited locale:", locale);

  if (!locales.includes(locale)) {
    console.warn(`[layout.tsx] Invalid locale: ${locale}`);
    notFound();
  }

  const messages = (await import(`../../messages/${locale}.json`)).default;
  const gtmId = process.env.NEXT_PUBLIC_GTM_ID || '';

  return (
    <html lang={locale} className={`${inter.variable} ${poppins.variable} ${dancingScript.variable}`}>
      <head>
        <link rel="icon" href="/favicon.png" />
        {/* Google Tag Manager */}
        {gtmId && (
          <script
            dangerouslySetInnerHTML={{
              __html: `(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
})(window,document,'script','dataLayer','${gtmId}');`,
            }}
          />
        )}
        {/* End Google Tag Manager */}
      </head>
      <NextIntlClientProvider locale={locale} messages={messages}>
      <body className="font-inter bg-[#F4F5F6] sm:bg-[#F8F5F0] relative overflow-x-hidden w-[100vw]">
        {/* Google Tag Manager (noscript) */}
        {gtmId && (
          <noscript>
            <iframe
              src={`https://www.googletagmanager.com/ns.html?id=${gtmId}`}
              height="0"
              width="0"
              style={{ display: 'none', visibility: 'hidden' }}
            />
          </noscript>
        )}
        {/* End Google Tag Manager (noscript) */}

          <Providers>
            <ToastProvider>
              {children}
              <div className="sticky z-[999999] bottom-10 right-10">
                {/* <AiBotMain /> */}
                <Analytics mode="production" />
           
              </div>
            </ToastProvider>
          </Providers>
        </body>
      </NextIntlClientProvider>
    </html>
  );
}
