// import "regenerator-runtime/runtime";
// import type { Metadata } from "next";
// import { Inter } from "next/font/google";
// import { Poppins } from "next/font/google";
// import "./globals.css";

// // Provider
// import { Providers } from "../providers";
// import AiBotMain from "@/components/AiChatBot/AiBotMain";
// import { Analytics } from '@vercel/analytics/react';

// import { notFound } from "next/navigation";
// import { NextIntlClientProvider, useMessages } from "next-intl";
// import { locales } from "@/navigation";
// import ToastProvider from "@/utils/ToastProvider";
// import 'react-datetime-picker/dist/DateTimePicker.css';
// import 'react-calendar/dist/Calendar.css';
// import 'react-clock/dist/Clock.css';

// const inter = Inter({
//   subsets: ["latin"],
//   variable: "--font-inter",
//   display: "swap",
// });

// const poppins = Poppins({
//   subsets: ["latin"],
//   variable: "--font-poppins",
//   display: "swap",
//   weight: "400",
// });

// export const metadata: Metadata = {
//   title: "Clinica San Miguel",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
//   params: { locale },
// }: {
//   children: React.ReactNode;
//   params: { locale: string };
// }) {
//   if (!locales.includes(locale)) {
//     notFound();
//   }

//   const messages = useMessages();

//   return (
//     <html lang={locale} className={`${inter.variable} ${poppins.variable}`}>
//       <head> <link rel="icon" href="/favicon.png"  /></head>
//       <NextIntlClientProvider locale={locale} messages={messages}>
//         <body className="font-inter bg-[#F8F5F0] relative overflow-x-hidden w-[100vw]">
//           <Providers>
//             <ToastProvider>
//               {" "}
              
//               {children}
//               <div
//                 className="sticky z-[999999] bottom-10 right-10"
//                 style={{ zIndex: 999999 }}
//               >
//                 <AiBotMain />
//                 <Analytics mode={'production'} />
//               </div>
//             </ToastProvider>
//           </Providers>
//         </body>
//       </NextIntlClientProvider>
//     </html>
//   );
// }


import "regenerator-runtime/runtime";
import type { Metadata } from "next";
import { Inter, Poppins } from "next/font/google";
import "./globals.css";

import { Providers } from "../providers";
import AiBotMain from "@/components/AiChatBot/AiBotMain";
import { Analytics } from "@vercel/analytics/react";
import { notFound } from "next/navigation";
import { NextIntlClientProvider } from "next-intl";
import { locales } from "@/navigation";
import ToastProvider from "@/utils/ToastProvider";
import 'react-datetime-picker/dist/DateTimePicker.css';
import 'react-calendar/dist/Calendar.css';
import 'react-clock/dist/Clock.css';
import WebChat from "@/components/WebChat";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  display: "swap",
});

const poppins = Poppins({
  subsets: ["latin"],
  variable: "--font-poppins",
  display: "swap",
  weight: "400",
});

export const metadata: Metadata = {
  title: "Clinica San Miguel",
  description: "Generated by create next app",
};

export default async function RootLayout(props: {
  children: React.ReactNode;
  params: Promise<{ locale: string }>; // ✅ handle param as a Promise
}) {
  const { children, params } = props;

  const resolvedParams = await params; // ✅ await it!
  const { locale } = resolvedParams;

  // 🐛 Optional Debug
  console.log("[layout.tsx] Awaited locale:", locale);

  if (!locales.includes(locale)) {
    console.warn(`[layout.tsx] Invalid locale: ${locale}`);
    notFound();
  }

  const messages = (await import(`../../messages/${locale}.json`)).default;

  return (
    <html lang={locale} className={`${inter.variable} ${poppins.variable}`}>
      <head>
        <link rel="icon" href="/favicon.png" />
      </head>
      <NextIntlClientProvider locale={locale} messages={messages}>
      <body className="font-inter bg-[#F4F5F6] sm:bg-[#F8F5F0] relative overflow-x-hidden w-[100vw]">


          <Providers>
            <ToastProvider>
              {children}
              <div className="sticky z-[999999] bottom-10 right-10">
                {/* <AiBotMain /> */}
                <Analytics mode="production" />
                <WebChat />
              </div>
            </ToastProvider>
          </Providers>
        </body>
      </NextIntlClientProvider>
    </html>
  );
}
