name: Simple Cypress Tests

on:
  push:
    branches:
      - mavra-testing

jobs:
  cypress-tests:
    name: Run Cypress Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22.x"
          cache: "yarn"

      - name: Install dependencies
        run: yarn install

      - name: Run Cypress Spanish Language Test
        run: yarn test:spanish
        continue-on-error: true

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-results
          path: |
            cypress/screenshots
            cypress/videos
          retention-days: 7
